[[KnotxServerOptions]]
== KnotxServerOptions

++++
 Describes a Knot.x HTTP Server configuration
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[accessLog]]`accessLog`|`link:cheatsheets.adoc#AccessLogOptions[AccessLogOptions]`|
+++
Set the access log options
+++
|[[allowedResponseHeaders]]`allowedResponseHeaders`|`Array of String`|
+++
Set the set of response headers that can be returned by the Knot.x server
+++
|[[backpressureBufferCapacity]]`backpressureBufferCapacity`|`Number (long)`|
+++
Sets the backpressure buffer capacity. Default value = 1000
+++
|[[backpressureStrategy]]`backpressureStrategy`|`link:cheatsheets.adoc#BackpressureOverflowStrategy[BackpressureOverflowStrategy]`|
+++
Sets the strategy how to deal with backpressure buffer overflow. Default is DROP_LATEST.

 Available values:
 <ul>
 <li>ERROR - terminates the whole sequence</li>
 <li>DROP_OLDEST - drops the oldest value from the buffer</li>
 <li>DROP_LATEST - drops the latest value from the buffer</li>
 </ul>
+++
|[[csrfConfig]]`csrfConfig`|`link:cheatsheets.adoc#KnotxCSRFOptions[KnotxCSRFOptions]`|
+++
Set the CSRF configuration of the Knot.x server
+++
|[[customFlow]]`customFlow`|`link:cheatsheets.adoc#KnotxFlowSettings[KnotxFlowSettings]`|
+++
Set the Custom Flow configuration
+++
|[[customResponseHeader]]`customResponseHeader`|`link:cheatsheets.adoc#CustomHttpHeader[CustomHttpHeader]`|
+++
Set the custom response header returned by the Knot.x
+++
|[[defaultFlow]]`defaultFlow`|`link:cheatsheets.adoc#KnotxFlowSettings[KnotxFlowSettings]`|
+++
Set the Default flow configuration
+++
|[[deliveryOptions]]`deliveryOptions`|`link:cheatsheets.adoc#DeliveryOptions[DeliveryOptions]`|
+++
Set the Event Bus Delivery options used to communicate with Knot's
+++
|[[displayExceptionDetails]]`displayExceptionDetails`|`Boolean`|
+++
Set whether to display or not the exception on error pages
+++
|[[dropRequestResponseCode]]`dropRequestResponseCode`|`Number (int)`|
+++
Sets the HTTP response code returned wheb request is dropped. Default is TOO_MANY_REQUESTS(429)
+++
|[[dropRequests]]`dropRequests`|`Boolean`|
+++
Enabled/disables request dropping (backpressure) on heavy load. Default is false - disabled.
+++
|[[fileUploadDirectory]]`fileUploadDirectory`|`String`|
+++
Set the location on Knot.x environment when uploaded files will be stored. These must be an absolute path.
+++
|[[fileUploadLimit]]`fileUploadLimit`|`Number (Long)`|
+++
Set the file upload limit in bytes
+++
|[[serverOptions]]`serverOptions`|`link:cheatsheets.adoc#HttpServerOptions[HttpServerOptions]`|
+++
Set the HTTP Server options
+++
|===
